### ISSUE TITLE
Avoid restart indexer due to broker partition leadership change

### ISSUE THREAD

**Issue by HenryCaiHaiying** [slackhq/astra#647]
### Describe the bug
When Kafka broker restarts, the Kafka partition leadership will change to other brokers.  The consumer fetch from the previous leader will fail due to network disconnect and fetch from the new leader will also fail because the previous fetch session handle is no longer valid.   Kafka consumer will throw OffsetOutofRangeException to Kaldb Indexer and indexer would fail and restart.

Kaldb Indexer restart is an expensive operation since it needs to rebuild the state.  We should try to avoid restart kaldb indexer by handling that OffsetException (retry the consumer.poll())

### Requirements (place an `x` in each of the `[ ]`)**
* [x] I've read and understood the [Contributing guidelines](../CONTRIBUTING.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

### To Reproduce
Shutdown a Kafka broker.

Saw the following exception and indexer restarts afterwards:

```
host:kaldb-index-traces-dev-3 log.message:FATAL: Unhandled exception @timestamp:Aug 14, 2023 @ 00:30:01.362 @version:1 error_message:Fetch position FetchPosition{offset=28770033742, offsetEpoch=Optional[86], currentLeader=LeaderAndEpoch{leader=Optional[events-a-kafka-dev-iad-zosl.nebula.tinyspeck.com:9092 (id: 1017 rack: us-east-1a)], epoch=87}} is out of range for partition kaldb_preprocessor-3
```

### Expected behavior
Kafdb indexer should handle that exception and retry the consumer.poll rather than restart

#### Reproducible in:

KalDB version:

JVM version:

OS version(s):

**Comment by vthacker** [comment]
I think we are still seeing this happen. Here is an example

```

`16:38:48.549, 16:38:51.568, 16:38:57.571, 16:39:06.575` - same message

[Consumer clientId=consumer-kaldb_index_<>_prod-1, groupId=kaldb_index_<>_prod] Fetch position FetchPosition{offset=37888803372, offsetEpoch=Optional[75], currentLeader=LeaderAndEpoch{leader=Optional[kafka.com:9092 (id: 1076 rack: us-east-1d)], epoch=absent}} is out of range for partition kaldb_preprocessor-144, raising error to the application since no reset policy is configured


16:38:48.559 - first retry (Caught unexpected exception, retry number: 0)
16:39:06.576 - 3rd retry (Caught unexpected exception, retry number: 3)
16:39:18.577 - FATAL: Unhandled exception`
16:39:18.582 - Running shutdown hook.	
16:40:01.573 - The highest durable offset for partition 144 is 37573180972
```
